# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.7-beta

core_version  = 2.0.4-26061500

mod_id=st
mod_name=Server Tools
mod_license=AM-CC-0
mod_version=26.2-2.0.0-260070300-Neo
mod_group_id=dev.anye.mc
mod_authors=[AnYe]AnMao(s)
mod_description=Website:https://anye.dev\nhttps://github.com/An-Mao/Servers