org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true

org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn

net.minecraftforge.gradle.merge-source-sets=true


minecraft_version=26.1.2
minecraft_version_range=[26.1.2,)
forge_version=64.0.8
forge_version_range=[64,)
loader_version_range=[64,)
mapping_channel = official
mapping_version = 26.1.2

core_version = 2.0.3-26041100

## Mod Properties
mod_id          = st
mod_name        = Server Tools
mod_license     = AM-CC-0
mod_version     = 26.1.2-2.0.0-26052400
mod_group_id    = dev.anye.mc
mod_authors     = [AnYe]AnMao(s)
mod_description = Website:https://anye.dev\nhttps://github.com/An-Mao/Servers